name: PHPStan Analysis

on:
  push:
    branches: ["master"]
    paths:
      - '.github/reporting.yml'
      - '**.php'
  pull_request:
    branches: ["master"]
    paths:
      - '.github/reporting.yml'
      - '**.php'

permissions:
  contents: write

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ./vendor
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Composer Init
        uses: php-actions/composer@v6
        with:
          php_version: "8.3"
          php_extensions: soap intl gd

      - name: PHPStan Analysis
        run: |
          ./vendor/bin/phpstan analyse --configuration=phpstan.neon --memory-limit=1024M --error-format=md --no-progress >> 'Static Analysis.md'

      - name: Wiki checkout
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}.wiki
          path: 'wiki'

      - name: Push
        run: |
          mv Coverage.md wiki
          mv 'Static Analysis.md' wiki
          cd wiki
          ls -la
          git config user.name actions-runner
          git config user.email actions-runner@github.com
          git add .
          git commit -m "Add Coverage and Analysis files" 
          git push
